Fix make tinygo-test
Don't use build/tinygo since it assumes that you are building llvm from
source

Example:

$ go install && make tinygo-test
cd tests/tinygotest && tinygo test
=== RUN   TestFail1
--- FAIL: TestFail1
	TestFail1 failed because of stuff and things

=== RUN   TestFail2
--- FAIL: TestFail2
	TestFail2 failed for reasons

=== RUN   TestPass
--- PASS: TestPass

exit status 2
FAIL